### ISSUE TITLE
tts和migpt部署在同一个服务器上，两个env文件如何区分？

### ISSUE THREAD

**Issue by shog86** [idootop/mi-gpt-tts#1]
如题

**Comment by shog86** [comment]
是把docker run -d --env-file $(pwd)/.env -p 4321:3000 idootop/mi-gpt-tts:latest

这儿的/.env

改成

/tts/.env

然后在root下面新建一个tts文件夹，把tts的env放进去吗？

**Comment by shog86** [comment]
不行。。。

**Comment by shog86** [comment]
// mi-gpt/.env
TTS_BASE_URL=http://[你的公网/局域网地址]:[端口号]/api

// mi-gpt/.migpt.js
export default {
  speaker: {
    // TTS 引擎
    tts: 'custom',
    // ...
  },
};

按这个部署完，看日志在生成答案，但最后并没有放出来。。。最后空白一大段，然后说说完了。。。

**Comment by idootop** [comment]
1. 确认你的 TTS 服务有没有启动成功
2. 确认浏览器访问http://[你的公网/局域网地址]:[端口号]/api/tts.mp3有没有声音
3. 确认你的小爱音箱连接的 wifi 能否正常访问 http://[你的公网/局域网地址]:[端口号]/api

**Comment by shog86** [comment]
是第一个问题，TTS服务没启动

我把tts的env参数也写在migpt的env里了，同一个env文件放在root下面，现在成了~

这个会在服务器上留下一堆mp3文件吗？

**Comment by idootop** [comment]
> 这个会在服务器上留下一堆mp3文件吗？

不会，音频数据流是实时合成的，并未保存到本地文件。

**Comment by shog86** [comment]
加了SECRET_PATH之后再运行，看日志只显示这个了
root@localhost:~# docker logs -f --tail 100 6263930f02a5
Server is running on port 3000

加的是

SECRET_PATH=

空值

**Comment by idootop** [comment]
@shog86  
1. 你用的tts服务的镜像不是最新版，更新到v3.0.0
2. SECRET_PATH 不能填空值

**Comment by shog86** [comment]
不是说留空会随机生成吗

**Comment by idootop** [comment]
没差，建议直接不填，而不是给个空字符串。另外最好自己设定个固定值，随机生成的话，容器重启之后又需要重新修改配置。
