### ISSUE TITLE
请问支持将音频缓存到服务器上么

### ISSUE THREAD

**Issue by mxyblog** [idootop/mi-gpt-tts#10]
目前生成的语音是每次都重复请求么？如果是的话，可以增加额外的配置选项将重复的请求音频缓存到服务区上么，这样可以减少请求次数和消耗。因为最近发现一个比较好的用处 就是可以作为小孩子学习拼音和汉字的发音辅助，一个字两个字那种，需要不断重复训练。

**Comment by idootop** [comment]
了解你的场景，不过考虑到LLM每次回复的内容一般都不相同，默认不会缓存音频到本地。

如果你熟悉js，可自行fork本项目添加缓存功能。

缓存功能实现指引：
1. 项目内已经有如何保存和读取本地音频文件并返回为http response的代码示例，可供参考
2. 考虑维护一个文本hash到本地音频文件的映射map，并标记过期时间，过期后自动清除记录和本地文件
