### ISSUE TITLE
在群晖的Docker中处理TTS请求时导致必现崩溃

### ISSUE THREAD

**Issue by donwang-ux** [idootop/mi-gpt-tts#11]
您好，

我在群晖NAS的Docker容器中运行MiGPT-TTS服务时遇到了一些问题。服务在最初启动时一切正常，但试用了一段时间后，容器会突然停止运行。

运行环境：群晖 DSM 7
服务版本：MiGPT-TTS v3.0.0

问题发生在我发送TTS请求时，并且每次都会出现。

非常感谢您开发的这个项目，它对我非常有帮助。希望您能提供一些指导或修复方案。

谢谢！

![image](https://github.com/user-attachments/assets/afed65d8-791c-4189-8f89-a183dd603629)

**Comment by idootop** [comment]
根据你提供的日志，错误来自于[解析 URL 请求参数](https://stackoverflow.com/questions/9064536/javascript-decodeuricomponent-malformed-uri-exception)时异常，显然你的 URI 未经过严格的 encodeURIComponent 编码。

建议：
1.检查你的请求参数 text 和 speaker 文本是否经过 encodeURIComponent 编码。
2. Docker 容器生命周期策略，改成退出后始终重启。
3. fork 本项目自行 catch 住编码异常，防止程序终止。

**Comment by dustookk** [comment]
@idootop 您好，我遇到了和楼主一样的问题，日志完全一样。 配置方式就是教程中的mi-gpt + mi-gpt-tts， 这两个服务结合还需要单独处理 中文encode的问题吗？  不知道您本地测试的时候是如何处理的

**Comment by idootop** [comment]
@donwang-ux 已修复，更新 Docker 镜像至 [v3.1.0](https://github.com/idootop/mi-gpt-tts/releases/tag/v3.1.0) 即可

**Comment by donwang-ux** [comment]
非常感谢！容器停止的问题已经解决了，但TTS仍然无法正常工作。我查看了Mi-GPT和MiGPT-TTS两个容器的日志，发现在Mi-GPT里返回的回答是中文字符，但在Mi-GPT-TTS中URI里的同样的中文字符被编码，导致无法正常合成。

日志请参考：
![image](https://github.com/user-attachments/assets/9d2fdc35-7325-45ad-945e-2fe8727ea969)

![image](https://github.com/user-attachments/assets/5b35a39d-dc2d-4692-a896-96cb6adb57bb)


再次感谢您的付出！

**Comment by idootop** [comment]
那么只剩一个可能：回答内容过长超出了合法的URL上限，超长的部分在访问时被截断。

打开 streamResponse 会降低这种情况发生的概率，此时长文本会被拆分成多段短文本依次 TTS，不过该功能需要你的小爱音箱支持查询到正确的播放状态才有效。

**Comment by donwang-ux** [comment]
非常感谢！在打开streamResponse后，可以正常播放语音结果了。

**Comment by yslemmo** [comment]
但是会导致ai在回答问题时，总是被中断
