### ISSUE TITLE
无界bncr插件版音色切换无效

### ISSUE THREAD

**Issue by haihaigege184** [idootop/mi-gpt-tts#15]
启动了服务，测试接口链接转语音正常，音箱提示切换成功，可实际还是小爱音色，哪里问题？

**Comment by idootop** [comment]
检查你的设置是否生效
<img width="747" alt="图片" src="https://github.com/user-attachments/assets/0cf6c4a9-6309-435e-969e-6cb0df2cec4a">

**Comment by haihaigege184** [comment]
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年11月26日(周二) 下午2:16
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [idootop/mi-gpt-tts] 无界bncr插件版音色切换无效 (Issue #15)




 
检查你的设置是否生效
 default.png (view on web)
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;



你好// TTS 引擎     tts: 'custom',此项变量插件未提供能更改的选项，插件加密也无法直接修改代码。可以在.env里面添加变量么？

**Comment by idootop** [comment]
不可以。自己联系插件作者开放配置参数吧

**Comment by haihaigege184** [comment]
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年11月26日(周二) 下午3:20
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [idootop/mi-gpt-tts] 无界bncr插件版音色切换无效 (Issue #15)




 
不可以。自己联系插件作者开放配置参数吧
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;




已解决，谢谢🙏
