### ISSUE TITLE
希望可以添加对火山引擎 tts 音调的支持. 细微的音调对于整体音色的改观很大.

### ISSUE THREAD

**Issue by wongchenv** [idootop/mi-gpt-tts#2]
<img width="1257" alt="image" src="https://github.com/idootop/mi-gpt-tts/assets/14831158/04b48ee5-37af-428f-8a14-4df79940446e">

**Comment by idootop** [comment]
这个项目只是MiGPT TTS 模块的一个简单的示例，仅用来展示如何实现 TTS 接口能力，更细节的需求可自行修改项目代码定制。
