### ISSUE TITLE
请问一下, 这个tts 可以用在其他地方吗?  

### ISSUE THREAD

**Issue by eachann1024** [idootop/mi-gpt-tts#4]
比如我在本地部署的 大模型, 把他作为朗读回答之类的.

**Comment by idootop** [comment]
可以的。不过火山语音合成单次文字长度上限为 1024 字节（UTF8），对于长文本的使用场景并未适配。

**Comment by eachann1024** [comment]
> 可以的。不过火山语音合成单次文字长度上限为 1024 字节（UTF8），对于长文本的使用场景并未适配。

懂了, 意外之喜 哈哈
