### ISSUE TITLE
更新后出现报错

### ISSUE THREAD

**Issue by Akj256** [idootop/mi-gpt-tts#7]
之前一直都是正常的，后面显示非法请求

**Comment by idootop** [comment]
请阅读文档中关于 `SECRET_PATH` 部分的说明。

**Comment by idootop** [comment]
@Akj256 3.0.0 版本新增了 `SECRET_PATH` 参数，要添加到 `TTS_BASE_URL` 路径里

<img width="1259" alt="图片" src="https://github.com/idootop/mi-gpt-tts/assets/35302658/0ccb2114-83f6-4e0b-91e8-637b99a864df">

**Comment by Akj256** [comment]
感谢，已解决此问题，祝工作生活愉快！
