### ISSUE TITLE
docker: poorly formatted environment: variable '<!DOCTYPE html>' contains whitespaces.

### ISSUE THREAD

**Issue by hipppo** [idootop/mi-gpt-tts#8]
docker: poorly formatted environment: variable '<!DOCTYPE html>' contains whitespaces.
![image](https://github.com/user-attachments/assets/806deb38-8e70-423a-9d00-c8135a06751d)

**Comment by idootop** [comment]
显然你设置的 .env 文件格式不正确，请参考 .env.example 模板自行解决。
