### ISSUE TITLE
在docker中运行失败

### ISSUE THREAD

**Issue by ccccccggggg** [idootop/mi-gpt-tts#9]
大佬你好，我在docker中运行migpt
跳登录失败原因是
code:'UNABLE_TO_VERIFY_LEAF_SIGNATURE',
message: 'unable to verify the first certificate'
以及初始化 Mi Services 失败
Error: ❌ Assertion failed大佬你知道怎么解决吗，谢谢🙏

**Comment by idootop** [comment]
你的网络访问小米的 https 地址证书验证失败，网络问题。

**Comment by idootop** [comment]
可以试试看这个，加个环境变量试试：https://stackoverflow.com/a/20100521

看起来是由代理代理引起的。
